name: 'Setup Python Environment'
description: 'Standardized Python environment setup with uv package manager'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/AppData/Local/uv/cache
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Install Python dependencies
      shell: bash
      run: uv pip install --system -e '.[dev]'
