/**
 * Type definitions for Intelligence Panel components
 *
 * These types define the data structures used by the Intelligence Panel to display
 * AI-generated insights, statistical anomalies, and talent distribution analytics.
 *
 * @see frontend/src/components/intelligence
 */

/**
 * Box position in the 9-box grid (1-9).
 *
 * Positions are numbered as follows:
 * ```
 *  7  8  9  (High Potential)
 *  4  5  6  (Medium Potential)
 *  1  2  3  (Low Potential)
 * (L)(M)(H) Performance
 * ```
 */
export type BoxPosition = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

/**
 * Severity level for anomalies.
 *
 * - `info`: Informational anomaly, no immediate action required
 * - `warning`: Moderate anomaly, review recommended
 * - `critical`: Severe anomaly, immediate attention required
 */
export type AnomalySeverity = "info" | "warning" | "critical";

/**
 * Type of statistical anomaly detected.
 *
 * - `location`: Geographical or organizational location bias
 * - `function`: Job function or department bias
 * - `distribution`: Uneven talent distribution across grid
 * - `outlier`: Statistical outliers in employee data
 */
export type AnomalyType = "location" | "function" | "distribution" | "outlier";

/**
 * Represents a statistical anomaly detected in talent distribution data.
 *
 * Anomalies are unusual patterns that may indicate calibration issues or
 * areas requiring attention in talent management. Each anomaly includes
 * a confidence score from the detection algorithm and optional suggestions
 * for remediation.
 */
export interface Anomaly {
  /** Unique identifier for the anomaly */
  id: string;

  /** Type of anomaly detected */
  type: AnomalyType;

  /** Severity level indicating urgency */
  severity: AnomalySeverity;

  /** Human-readable title describing the anomaly */
  title: string;

  /** Detailed description explaining what was detected */
  description: string;

  /** Array of employee IDs affected by this anomaly */
  affectedEmployees: string[];

  /** Optional suggestion for remediation */
  suggestion?: string;

  /** AI confidence score (0-1) for this anomaly detection */
  confidence: number;
}

/**
 * Type of AI-generated insight.
 *
 * - `recommendation`: Actionable suggestion for improvement
 * - `observation`: Noteworthy pattern or trend
 * - `warning`: Potential concern requiring attention
 */
export type InsightType = "recommendation" | "observation" | "warning";

/**
 * Represents an AI-generated insight about talent distribution.
 *
 * Insights are observations and recommendations generated by analyzing
 * talent distribution patterns. Each insight includes a confidence score
 * and optional action button with metadata about affected employees.
 */
export interface Insight {
  /** Unique identifier for the insight */
  id: string;

  /** Type of insight (recommendation/observation/warning) */
  type: InsightType;

  /** Human-readable insight text */
  text: string;

  /** AI confidence score (0-1) for this insight */
  confidence: number;

  /** Optional label for action button (e.g., "View employees", "Export list") */
  actionLabel?: string;

  /** Optional metadata about affected employees and grid positions */
  metadata?: {
    /** Number of employees affected by this insight */
    employeeCount?: number;

    /** Grid positions affected by this insight */
    affectedBoxes?: BoxPosition[];
  };
}

/**
 * Represents distribution data for a single grid position.
 *
 * Contains employee count, percentage, and label for one of the
 * nine positions in the talent grid.
 */
export interface DistributionSegment {
  /** Grid position (1-9) */
  position: BoxPosition;

  /** Number of employees in this position */
  count: number;

  /** Percentage of total employees in this position */
  percentage: number;

  /** Human-readable label for this position (e.g., "Low/Low", "High/High") */
  label: string;
}

/**
 * Represents complete talent distribution data across all grid positions.
 *
 * Includes distribution segments for all positions, total employee count,
 * and ideal distribution percentages for comparison.
 */
export interface DistributionData {
  /** Distribution data for all nine grid positions */
  segments: DistributionSegment[];

  /** Total number of employees across all positions */
  total: number;

  /** Expected ideal distribution percentages by position (position as string key) */
  idealPercentages: { [key: string]: number };
}

/**
 * Props for the main Intelligence Panel component.
 *
 * Controls all data display and interactions for anomalies, insights,
 * and distribution analytics.
 */
export interface IntelligencePanelProps {
  /** List of detected anomalies to display */
  anomalies: Anomaly[];

  /** List of AI-generated insights to display */
  insights: Insight[];

  /** Talent distribution data across grid positions */
  distribution: DistributionData;

  /** Whether data is currently loading */
  isLoading: boolean;

  /** Optional error message to display */
  error?: string;

  /** Callback when an anomaly card is clicked */
  onAnomalyClick?: (anomaly: Anomaly) => void;

  /** Callback when an anomaly is dismissed */
  onAnomalyDismiss?: (anomalyId: string) => void;

  /** Callback when an insight action button is clicked */
  onInsightAction?: (insightId: string) => void;

  /** Callback to refresh intelligence data */
  onRefresh?: () => void;

  /** Callback to export intelligence data */
  onExport?: () => void;
}

/**
 * Props for the AnomalyCard component.
 *
 * Controls display and interaction for a single anomaly card.
 */
export interface AnomalyCardProps {
  /** Anomaly data to display */
  anomaly: Anomaly;

  /** Optional callback when dismiss button is clicked */
  onDismiss?: (id: string) => void;

  /** Optional callback when card is clicked */
  onClick?: (anomaly: Anomaly) => void;

  /** Whether to show action buttons (dismiss, expand) */
  showActions?: boolean;
}

/**
 * Props for the InsightCard component.
 *
 * Controls display and interaction for a single insight card.
 */
export interface InsightCardProps {
  /** Insight data to display */
  insight: Insight;

  /** Optional callback when action button is clicked */
  onAction?: (id: string) => void;

  /** Whether to show confidence indicator (progress bar and badge) */
  showConfidence?: boolean;
}

/**
 * Props for distribution chart components.
 *
 * Controls display and interaction for distribution visualizations.
 */
export interface DistributionChartProps {
  /** Distribution data to visualize */
  data: DistributionData;

  /** Whether to show position labels on chart */
  showLabels?: boolean;

  /** Whether chart segments are clickable */
  interactive?: boolean;

  /** Optional callback when a chart segment is clicked */
  onSegmentClick?: (position: BoxPosition) => void;
}
