/**
 * Create macOS .icns file from PNG sources using native iconutil
 *
 * This script creates a multi-resolution .icns file for macOS builds.
 * It uses the PNG files generated by generate_logo_icons.ts and the
 * macOS native iconutil command-line tool.
 */

import { execSync } from "child_process";
import { copyFileSync, mkdirSync, rmSync, existsSync } from "fs";
import { join } from "path";

async function createIcns() {
  const buildDir = join(__dirname, "..", "build");
  const iconsetDir = join(buildDir, "icon.iconset");

  console.log("Creating macOS .icns file using iconutil...");
  console.log("=".repeat(50));

  // Check if running on macOS
  if (process.platform !== "darwin") {
    console.error("\n[ERROR] iconutil is only available on macOS");
    console.error("This script must be run on macOS or in macOS CI");
    process.exit(1);
  }

  // Create iconset directory
  if (existsSync(iconsetDir)) {
    rmSync(iconsetDir, { recursive: true });
  }
  mkdirSync(iconsetDir, { recursive: true });

  // iconutil requires specific naming:
  // icon_16x16.png, icon_16x16@2x.png (which is 32x32), etc.
  const iconMapping = [
    { src: "icon_16x16.png", dest: "icon_16x16.png" },
    { src: "icon_32x32.png", dest: "icon_16x16@2x.png" },
    { src: "icon_32x32.png", dest: "icon_32x32.png" },
    { src: "icon_64x64.png", dest: "icon_32x32@2x.png" },
    { src: "icon_128x128.png", dest: "icon_128x128.png" },
    { src: "icon_256x256.png", dest: "icon_128x128@2x.png" },
    { src: "icon_256x256.png", dest: "icon_256x256.png" },
    { src: "icon_512x512.png", dest: "icon_256x256@2x.png" },
    { src: "icon_512x512.png", dest: "icon_512x512.png" },
    { src: "icon_1024x1024.png", dest: "icon_512x512@2x.png" },
  ];

  // Copy PNG files to iconset with correct naming
  console.log("\nCopying PNG files to iconset...");
  for (const { src, dest } of iconMapping) {
    const srcPath = join(buildDir, src);
    const destPath = join(iconsetDir, dest);

    if (!existsSync(srcPath)) {
      console.warn(`[WARN] Missing ${src}, skipping ${dest}`);
      continue;
    }

    copyFileSync(srcPath, destPath);
    console.log(`[OK] ${dest}`);
  }

  // Run iconutil to create .icns file
  console.log("\nRunning iconutil...");
  try {
    execSync(`iconutil -c icns "${iconsetDir}"`, {
      cwd: buildDir,
      stdio: "inherit",
    });

    const icnsPath = join(buildDir, "icon.icns");
    console.log(`\n[SUCCESS] Created ${icnsPath}`);

    // Clean up iconset directory
    rmSync(iconsetDir, { recursive: true });
    console.log("[OK] Cleaned up temporary iconset directory");
  } catch (error) {
    console.error("\n[ERROR] Failed to create ICNS file:", error);
    console.error("Make sure iconutil is available (macOS only)");
    process.exit(1);
  }
}

createIcns().catch((error) => {
  console.error("\n[ERROR]", error);
  process.exit(1);
});
