/**
 * Create macOS .icns file from PNG sources
 *
 * This script creates a multi-resolution .icns file for macOS builds.
 * It uses the PNG files generated by generate_logo_icons.ts
 */

import * as png2icons from "png2icons";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

async function createIcns() {
  const buildDir = join(__dirname, "..", "build");

  // Required sizes for macOS icns (in order of priority)
  // macOS iconutil requires specific sizes
  const sizes = [16, 32, 64, 128, 256, 512, 1024];

  console.log("Creating macOS .icns file...");
  console.log("=".repeat(50));

  // Load PNG files
  const pngFiles: Buffer[] = [];
  for (const size of sizes) {
    const pngPath = join(buildDir, `icon_${size}x${size}.png`);
    try {
      const buffer = readFileSync(pngPath);
      pngFiles.push(buffer);
      console.log(`[OK] Loaded ${size}x${size} PNG`);
    } catch (error) {
      console.error(`[SKIP] Missing ${size}x${size} PNG, skipping`);
    }
  }

  if (pngFiles.length === 0) {
    console.error("\n[ERROR] No PNG files found!");
    process.exit(1);
  }

  // Check for minimum required sizes
  if (!readFileSync(join(buildDir, "icon_512x512.png"))) {
    console.error("\n[ERROR] 512x512 PNG is required!");
    process.exit(1);
  }

  try {
    // Create ICNS file
    // png2icons expects an array of PNG buffers
    const icnsBuffer = png2icons.createICNS(
      pngFiles,
      png2icons.BILINEAR,
      0 // threshold
    );

    // Save ICNS file
    const icnsPath = join(buildDir, "icon.icns");
    writeFileSync(icnsPath, icnsBuffer);

    console.log(`\n[SUCCESS] Created ${icnsPath}`);
    console.log(`  File size: ${icnsBuffer.length.toLocaleString()} bytes`);
    console.log(`  Resolutions included: ${pngFiles.length}`);
  } catch (error) {
    console.error("\n[ERROR] Failed to create ICNS file:", error);
    console.error(
      '\nNote: If you see "Failed to create ICNS", you may need to'
    );
    console.error("use macOS iconutil or an online converter instead.");
    process.exit(1);
  }
}

createIcns().catch((error) => {
  console.error("\n[ERROR]", error);
  process.exit(1);
});
