#!/usr/bin/env tsx
/**
 * Generate Design Tokens CSS for Documentation
 *
 * This script reads the TypeScript design tokens from frontend/src/theme/tokens.ts
 * and generates a CSS file with custom properties for use in the MkDocs documentation.
 *
 * This ensures the documentation design system stays in sync with the application.
 *
 * Usage:
 *   npm run generate:docs-tokens
 *   or: npx tsx scripts/generate-docs-tokens.ts
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { tokens } from "../src/theme/tokens";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Convert camelCase to kebab-case
 */
function toKebabCase(str: string): string {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/**
 * Recursively generate CSS custom properties from a nested object
 */
function generateCSSVars(
  obj: Record<string, any>,
  prefix: string = ""
): string[] {
  const vars: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${toKebabCase(key)}` : toKebabCase(key);

    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      // Recursively process nested objects
      vars.push(...generateCSSVars(value, varName));
    } else {
      // Convert value to CSS-compatible format
      let cssValue: string;

      if (typeof value === "number") {
        cssValue = `${value}px`;
      } else if (Array.isArray(value)) {
        cssValue = value.join(", ");
      } else {
        cssValue = String(value);
      }

      vars.push(`  --${varName}: ${cssValue};`);
    }
  }

  return vars;
}

/**
 * Generate the complete CSS file content
 */
function generateCSS(): string {
  const lines: string[] = [];

  // Header
  lines.push("/**");
  lines.push(" * 9Boxer Design Tokens for Documentation");
  lines.push(" *");
  lines.push(" * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY");
  lines.push(" * Generated from: frontend/src/theme/tokens.ts");
  lines.push(" * Generated by: frontend/scripts/generate-docs-tokens.ts");
  lines.push(" *");
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(" *");
  lines.push(" * To regenerate:");
  lines.push(" *   npm run generate:docs-tokens");
  lines.push(" */");
  lines.push("");

  // Generate light mode tokens (default)
  lines.push(
    "/* ============================================================================"
  );
  lines.push("   LIGHT MODE TOKENS (Default)");
  lines.push(
    "   ============================================================================ */"
  );
  lines.push("");
  lines.push(":root {");

  // Colors - Light mode
  lines.push("  /* Primary Colors */");
  lines.push(...generateCSSVars(tokens.colors.primary.light, "color-primary"));
  lines.push("");

  lines.push("  /* Secondary Colors */");
  lines.push(
    ...generateCSSVars(tokens.colors.secondary.light, "color-secondary")
  );
  lines.push("");

  lines.push("  /* Background Colors */");
  lines.push(
    ...generateCSSVars(tokens.colors.background.light, "color-background")
  );
  lines.push("");

  lines.push("  /* Text Colors */");
  lines.push(...generateCSSVars(tokens.colors.text.light, "color-text"));
  lines.push("");

  lines.push("  /* Semantic Colors */");
  lines.push(...generateCSSVars(tokens.colors.semantic, "color-semantic"));
  lines.push("");

  lines.push("  /* Grid Box Colors */");
  lines.push(...generateCSSVars(tokens.colors.gridBox.light, "color-grid-box"));
  lines.push("");

  lines.push("  /* Chart Colors */");
  lines.push(...generateCSSVars(tokens.colors.charts.light, "color-chart"));
  lines.push("");

  lines.push("  /* Scrollbar Colors */");
  lines.push(
    ...generateCSSVars(tokens.colors.scrollbar.light, "color-scrollbar")
  );
  lines.push("");

  // Spacing
  lines.push("  /* Spacing Scale (8px grid) */");
  lines.push(...generateCSSVars(tokens.spacing, "spacing"));
  lines.push("");

  // Typography
  lines.push("  /* Typography - Font Family */");
  lines.push(`  --typography-font-family: ${tokens.typography.fontFamily};`);
  lines.push("");

  lines.push("  /* Typography - Font Sizes */");
  lines.push(
    ...generateCSSVars(tokens.typography.fontSize, "typography-font-size")
  );
  lines.push("");

  lines.push("  /* Typography - Font Weights */");
  Object.entries(tokens.typography.fontWeight).forEach(([key, value]) => {
    lines.push(`  --typography-font-weight-${toKebabCase(key)}: ${value};`);
  });
  lines.push("");

  lines.push("  /* Typography - Line Heights */");
  Object.entries(tokens.typography.lineHeight).forEach(([key, value]) => {
    lines.push(`  --typography-line-height-${toKebabCase(key)}: ${value};`);
  });
  lines.push("");

  // Border Radius
  lines.push("  /* Border Radius */");
  Object.entries(tokens.radius).forEach(([key, value]) => {
    const cssValue = typeof value === "number" ? `${value}px` : value;
    lines.push(`  --radius-${toKebabCase(key)}: ${cssValue};`);
  });
  lines.push("");

  // Shadows - Light mode
  lines.push("  /* Shadows */");
  Object.entries(tokens.shadows).forEach(([key, value]) => {
    if (typeof value === "object" && "light" in value) {
      lines.push(`  --shadow-${toKebabCase(key)}: ${value.light};`);
    }
  });
  lines.push("");

  // Duration
  lines.push("  /* Animation Duration */");
  lines.push(...generateCSSVars(tokens.duration, "duration"));
  lines.push("");

  // Easing
  lines.push("  /* Animation Easing */");
  lines.push(...generateCSSVars(tokens.easing, "easing"));
  lines.push("");

  // Opacity
  lines.push("  /* Opacity Levels */");
  Object.entries(tokens.opacity).forEach(([key, value]) => {
    lines.push(`  --opacity-${toKebabCase(key)}: ${value};`);
  });
  lines.push("");

  // Z-Index
  lines.push("  /* Z-Index Scale */");
  Object.entries(tokens.zIndex).forEach(([key, value]) => {
    lines.push(`  --z-index-${toKebabCase(key)}: ${value};`);
  });
  lines.push("");

  // Dimensions - Scrollbar
  lines.push("  /* Scrollbar Dimensions */");
  lines.push(
    ...generateCSSVars(tokens.dimensions.scrollbar, "dimension-scrollbar")
  );

  lines.push("}");
  lines.push("");

  // Generate dark mode tokens
  lines.push(
    "/* ============================================================================"
  );
  lines.push("   DARK MODE TOKENS");
  lines.push(
    "   ============================================================================ */"
  );
  lines.push("");
  lines.push('[data-md-color-scheme="slate"] {');

  // Colors - Dark mode
  lines.push("  /* Primary Colors (Dark) */");
  lines.push(...generateCSSVars(tokens.colors.primary.dark, "color-primary"));
  lines.push("");

  lines.push("  /* Secondary Colors (Dark) */");
  lines.push(
    ...generateCSSVars(tokens.colors.secondary.dark, "color-secondary")
  );
  lines.push("");

  lines.push("  /* Background Colors (Dark) */");
  lines.push(
    ...generateCSSVars(tokens.colors.background.dark, "color-background")
  );
  lines.push("");

  lines.push("  /* Text Colors (Dark) */");
  lines.push(...generateCSSVars(tokens.colors.text.dark, "color-text"));
  lines.push("");

  lines.push("  /* Grid Box Colors (Dark) */");
  lines.push(...generateCSSVars(tokens.colors.gridBox.dark, "color-grid-box"));
  lines.push("");

  lines.push("  /* Chart Colors (Dark) */");
  lines.push(...generateCSSVars(tokens.colors.charts.dark, "color-chart"));
  lines.push("");

  lines.push("  /* Scrollbar Colors (Dark) */");
  lines.push(
    ...generateCSSVars(tokens.colors.scrollbar.dark, "color-scrollbar")
  );
  lines.push("");

  // Shadows - Dark mode
  lines.push("  /* Shadows (Dark) */");
  Object.entries(tokens.shadows).forEach(([key, value]) => {
    if (typeof value === "object" && "dark" in value) {
      lines.push(`  --shadow-${toKebabCase(key)}: ${value.dark};`);
    }
  });

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Main execution
 */
function main() {
  console.log("🎨 Generating design tokens CSS for documentation...");

  const css = generateCSS();
  const outputPath = join(
    __dirname,
    "../../resources/user-guide/docs/stylesheets/design-tokens.css"
  );

  writeFileSync(outputPath, css, "utf8");

  console.log(
    "✅ Generated: resources/user-guide/docs/stylesheets/design-tokens.css"
  );
  console.log("");
  console.log("📊 Token Summary:");
  console.log(`   - Colors: ${Object.keys(tokens.colors).length} categories`);
  console.log(`   - Spacing: ${Object.keys(tokens.spacing).length} scales`);
  console.log(
    `   - Typography: ${Object.keys(tokens.typography.fontSize).length} sizes`
  );
  console.log(`   - Radius: ${Object.keys(tokens.radius).length} scales`);
  console.log(`   - Shadows: ${Object.keys(tokens.shadows).length} levels`);
  console.log("");
  console.log("💡 Next steps:");
  console.log("   1. Review the generated CSS file");
  console.log("   2. Update extra.css to use the new CSS custom properties");
  console.log("   3. Run 'mkdocs serve' to preview changes");
}

main();
